-- MySQL Script generated by MySQL Workbench
-- Mi 27 Mai 2020 20:09:04 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SWADB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SWADB` ;

-- -----------------------------------------------------
-- Schema SWADB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SWADB` DEFAULT CHARACTER SET utf8 ;
USE `SWADB` ;

-- -----------------------------------------------------
-- Table `SWADB`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SWADB`.`company` ;

CREATE TABLE IF NOT EXISTS `SWADB`.`company` (
  `idcompany` INT NOT NULL,
  `companyname` VARCHAR(45) NULL,
  `department` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`idcompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWADB`.`swauser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SWADB`.`swauser` ;

CREATE TABLE IF NOT EXISTS `SWADB`.`swauser` (
  `iduser` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `is_admin` TINYINT NULL,
  `company_idcompany` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_company_idx` (`company_idcompany` ASC) VISIBLE,
  CONSTRAINT `fk_user_company`
    FOREIGN KEY (`company_idcompany`)
    REFERENCES `SWADB`.`company` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `SWADB`.`servicecontract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SWADB`.`servicecontract` ;

CREATE TABLE IF NOT EXISTS `SWADB`.`servicecontract` (
  `idservicecontract` INT NOT NULL,
  `startdate` DATETIME NULL,
  `enddate` DATETIME NULL,
  `company_idcompany` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idservicecontract`),
  INDEX `fk_servicecontract_company1_idx` (`company_idcompany` ASC) VISIBLE,
  INDEX `fk_servicecontract_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_servicecontract_company1`
    FOREIGN KEY (`company_idcompany`)
    REFERENCES `SWADB`.`company` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicecontract_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `SWADB`.`swauser` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWADB`.`license`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SWADB`.`license` ;

CREATE TABLE IF NOT EXISTS `SWADB`.`license` (
  `idlicense` INT NOT NULL,
  `expirationdate` DATETIME NULL,
  `licensekey` VARCHAR(45) NULL,
  `IP1` VARCHAR(45) NULL,
  `IP2` VARCHAR(45) NULL,
  `IP3` VARCHAR(45) NULL,
  `IP4` VARCHAR(45) NULL,
  `licensecount` INT NULL,
  `servicecontract_idservicecontract` INT NOT NULL,
  PRIMARY KEY (`idlicense`, `servicecontract_idservicecontract`),
  INDEX `fk_license_servicecontract1_idx` (`servicecontract_idservicecontract` ASC) VISIBLE,
  CONSTRAINT `fk_license_servicecontract1`
    FOREIGN KEY (`servicecontract_idservicecontract`)
    REFERENCES `SWADB`.`servicecontract` (`idservicecontract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
